[package]
name = "sekirei"
version = "0.3.46"
edition = "2024"
description = "USI shogi engine binary (Sekirei)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kent-tokyo/sekirei"

[[bin]]
name = "sekirei"
path = "src/main.rs"

[dependencies]
sekirei-core = { path = "../sekirei-core", version = "0.3.46" }
rayon = "1"
lineprior = "0.12.0"

[features]
king_relative_b_small = ["sekirei-core/king_relative_b_small"]
nnue_l1_384 = ["sekirei-core/nnue_l1_384"]
nnue_l1_128 = ["sekirei-core/nnue_l1_128"]
nnue_l2_64 = ["sekirei-core/nnue_l2_64"]
nnue_l2_16 = ["sekirei-core/nnue_l2_16"]
